import { useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { isLoggedIn } from "@/lib/auth";
import {
  FileText, Mail, Search, Mic, ArrowRight, Upload, MessageSquare, Sparkles,
  Bot, Shield, Zap, Users
} from "lucide-react";

export default function Landing() {
  const navigate = useNavigate();

  useEffect(() => {
    if (isLoggedIn()) navigate("/dashboard");
  }, [navigate]);

  return (
    <div className="min-h-screen bg-background animate-slide-up">
      {/* Hero */}
      <section className="relative overflow-hidden pt-32 pb-20">
        {/* Background glow */}
        <div className="pointer-events-none absolute inset-0">
          <div className="absolute -top-32 left-1/2 h-[500px] w-[500px] -translate-x-1/2 rounded-full bg-primary/20 blur-[120px]" />
          <div className="absolute bottom-0 right-1/4 h-[400px] w-[400px] rounded-full bg-primary/10 blur-[100px]" />
        </div>

        <div className="relative max-w-5xl mx-auto px-6 text-center">
          <div className="inline-flex items-center gap-2 bg-primary/10 text-primary border border-primary/20 px-4 py-1.5 rounded-full text-sm font-medium mb-8 animate-fade-in">
            <Sparkles className="w-4 h-4" />
            Powered by Multi-Agent AI
          </div>

          <h1 className="text-4xl md:text-6xl lg:text-7xl font-bold mb-8 tracking-tight leading-tight">
            Land Your Dream Job{" "}
            <span className="gradient-text">Effortlessly</span>
          </h1>

          <p className="text-lg md:text-xl text-muted-foreground mb-12 max-w-2xl mx-auto leading-relaxed">
            Upload your CV once. Paste any job description. Get a tailored resume,
            personalized cover letter, company research, and interview prep — all
            generated by specialized AI agents.
          </p>

          <div className="flex justify-center">
            <Link
              to="/login"
              className="bg-primary text-primary-foreground px-10 py-4 rounded-xl text-lg font-bold hover:opacity-90 transition-all shadow-lg shadow-primary/25 hover:shadow-primary/40 w-full sm:w-auto transform hover:-translate-y-1"
            >
              Get Started Free
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="bg-secondary/20 py-24 border-y border-border/50">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-bold mb-4 tracking-tight">
              Six AI Agents Working For You
            </h2>
          <p className="text-muted-foreground max-w-xl mx-auto">
            Each agent specializes in a different part of the job application process
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <FeatureCard
            icon={<FileText className="w-6 h-6" />}
            title="ATS Resume Builder"
            description="Tailored, ATS-optimized resume using your real experience matched to the job keywords"
          />
          <FeatureCard
            icon={<Mail className="w-6 h-6" />}
            title="Cover Letter Writer"
            description="Personalized letter referencing company values, news, and your top achievements"
          />
          <FeatureCard
            icon={<Search className="w-6 h-6" />}
            title="Company Researcher"
            description="Culture, recent news, tech stack, and interview insights from web research"
          />
            <FeatureCard
              icon={<Mic className="w-6 h-6" />}
              title="Interview Coach"
              description="10 likely questions with STAR-format answers crafted from your experience"
            />
          </div>
        </div>
      </section>

      {/* How it works */}
      <section className="relative py-24 overflow-hidden border-t border-border/50">
        <div className="max-w-6xl mx-auto px-6 relative z-10">
          <div className="text-center mb-16">
            <h2 className="text-3xl md:text-5xl font-bold mb-4 tracking-tight">
              How It Works
            </h2>
            <p className="text-muted-foreground max-w-xl mx-auto">
              Three simple steps to supercharge your job search
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-12">
            <StepCard
              step={1}
              icon={<Upload className="w-6 h-6" />}
              title="Upload Your CV"
              description="Upload your CV once (PDF, DOCX, or TXT). Our AI extracts and indexes your experience, skills, and achievements."
            />
            <StepCard
              step={2}
              icon={<MessageSquare className="w-6 h-6" />}
              title="Paste a Job Description"
              description="Drop any job posting into the chat. Our agents detect it automatically and start working."
            />
            <StepCard
              step={3}
              icon={<Sparkles className="w-6 h-6" />}
              title="Get Everything Tailored"
              description="In 1-2 minutes, receive a complete application package: resume, cover letter, research, and interview prep."
            />
          </div>
        </div>
      </section>

      {/* Trust / Benefits */}
      <section className="bg-secondary/20 py-24 border-y border-border/50">
        <div className="max-w-6xl mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="flex items-start gap-3 p-6 rounded-2xl glass border-primary/10">
            <Shield className="w-6 h-6 text-primary flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-bold mb-2 text-foreground">Your Data, Isolated</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">Each user gets their own Pinecone namespace. Your data is never mixed with others.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 p-6 rounded-2xl glass border-primary/10">
            <Zap className="w-6 h-6 text-primary flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-bold mb-2 text-foreground">Never Fabricates</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">Agents only use YOUR real experience. Nothing is invented or hallucinated.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 p-6 rounded-2xl glass border-primary/10">
            <Users className="w-6 h-6 text-primary flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-bold mb-2 text-foreground">Built by AI Agents</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">CrewAI-powered agents collaborate like a team of career coaches working just for you.</p>
            </div>
          </div>
        </div>
      </div>
    </section>

      {/* CTA */}
      <section className="relative py-20 overflow-hidden">
        <div className="absolute inset-0 bg-primary/5 blur-[100px]" />
        <div className="relative max-w-4xl mx-auto px-6 text-center">
          <Bot className="w-16 h-16 mx-auto mb-6 text-primary animate-pulse" />
          <h2 className="text-3xl md:text-5xl font-bold mb-6">
            Ready to land your next role?
          </h2>
          <p className="text-xl text-muted-foreground mb-10">
            Create your account, upload your CV, and let the AI agents do the heavy lifting.
          </p>
          <Link
            to="/login"
            className="inline-flex items-center gap-2 bg-primary text-primary-foreground px-10 py-4 rounded-xl text-lg font-bold hover:opacity-90 transition-all shadow-lg shadow-primary/20 btn-hover"
          >
            Start Now — It's Free
            <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-border/50 bg-background/50 backdrop-blur-md py-12">
        <div className="max-w-6xl mx-auto px-6 text-center">
          <div className="flex items-center justify-center gap-2 mb-4">
            <Sparkles className="w-5 h-5 text-primary" />
            <span className="font-display font-bold text-xl">ResumeCrew<span className="text-primary">.</span></span>
          </div>
          <p className="text-muted-foreground text-sm font-medium">
            ResumeCrew — Powered by CrewAI, Groq & Local Embeddings
          </p>
        </div>
      </footer>
    </div>
  );
}

function FeatureCard({ icon, title, description }: {
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <div className="glass p-8 rounded-2xl border-white/5 hover:border-primary/30 transition-all duration-300 group">
      <div className="w-12 h-12 bg-primary/10 rounded-xl flex items-center justify-center text-primary mb-6 transition-transform group-hover:scale-110">
        {icon}
      </div>
      <h3 className="font-bold text-xl mb-3 text-foreground">{title}</h3>
      <p className="text-muted-foreground text-sm leading-relaxed">{description}</p>
    </div>
  );
}

function StepCard({ step, icon, title, description }: {
  step: number;
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <div className="text-center group">
      <div className="relative inline-flex items-center justify-center w-20 h-20 bg-primary/10 text-primary rounded-3xl mb-6 transition-all duration-300 group-hover:scale-110 group-hover:bg-primary/20 border border-primary/20">
        {icon}
        <span className="absolute -top-2 -right-2 w-8 h-8 bg-primary text-primary-foreground rounded-full text-sm font-bold flex items-center justify-center shadow-lg shadow-primary/30">
          {step}
        </span>
      </div>
      <h3 className="font-bold text-xl mb-3 text-foreground">{title}</h3>
      <p className="text-muted-foreground text-sm leading-relaxed">{description}</p>
    </div>
  );
}
