import { useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import { isLoggedIn } from "../lib/auth";
import {
  FileText, Mail, Search, Mic, ArrowRight, Upload, MessageSquare, Sparkles,
  Bot, Shield, Zap, Users
} from "lucide-react";

export default function Landing() {
  const navigate = useNavigate();

  useEffect(() => {
    if (isLoggedIn()) navigate("/dashboard");
  }, [navigate]);

  return (
    <div className="min-h-[calc(100vh-57px)]">
      {/* Hero */}
      <section className="relative overflow-hidden">
        <div className="absolute inset-0 bg-gradient-to-br from-blue-50 via-violet-50 to-pink-50" />
        <div className="absolute inset-0 opacity-30" style={{
          backgroundImage: `radial-gradient(circle at 25% 25%, rgba(99,102,241,0.1) 0%, transparent 50%),
                           radial-gradient(circle at 75% 75%, rgba(168,85,247,0.1) 0%, transparent 50%)`
        }} />

        <div className="relative max-w-5xl mx-auto px-4 py-20 md:py-28 text-center">
          <div className="inline-flex items-center gap-2 bg-blue-100 text-blue-700 px-4 py-1.5 rounded-full text-sm font-medium mb-6">
            <Sparkles className="w-4 h-4" />
            Powered by Multi-Agent AI
          </div>

          <h1 className="text-4xl md:text-6xl font-bold mb-6 bg-gradient-to-r from-gray-900 via-blue-800 to-violet-700 bg-clip-text text-transparent leading-tight">
            ResumeCrew:<br />AI Job Application Agent
          </h1>

          <p className="text-lg md:text-xl text-gray-600 mb-10 max-w-2xl mx-auto leading-relaxed">
            Upload your CV once. Paste any job description. Get a tailored resume,
            personalised cover letter, company research, and interview prep — all
            generated by specialized AI agents.
          </p>

          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <Link
              to="/register"
              className="inline-flex items-center justify-center gap-2 bg-blue-600 text-white px-8 py-3.5 rounded-xl text-lg font-medium hover:bg-blue-700 transition shadow-lg shadow-blue-600/25 hover:shadow-xl hover:shadow-blue-600/30"
            >
              Get Started Free
              <ArrowRight className="w-5 h-5" />
            </Link>
            <Link
              to="/login"
              className="inline-flex items-center justify-center gap-2 bg-white text-gray-700 border-2 border-gray-200 px-8 py-3.5 rounded-xl text-lg font-medium hover:border-blue-300 hover:text-blue-600 transition"
            >
              Login
            </Link>
          </div>
        </div>
      </section>

      {/* Features */}
      <section className="max-w-5xl mx-auto px-4 py-16">
        <h2 className="text-2xl md:text-3xl font-bold text-center mb-3">
          Six AI Agents Working For You
        </h2>
        <p className="text-gray-500 text-center mb-12 max-w-xl mx-auto">
          Each agent specializes in a different part of the job application process
        </p>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
          <FeatureCard
            icon={<FileText className="w-6 h-6" />}
            color="blue"
            title="ATS Resume Builder"
            description="Tailored, ATS-optimised resume using your real experience matched to the job keywords"
          />
          <FeatureCard
            icon={<Mail className="w-6 h-6" />}
            color="violet"
            title="Cover Letter Writer"
            description="Personalised letter referencing company values, news, and your top achievements"
          />
          <FeatureCard
            icon={<Search className="w-6 h-6" />}
            color="emerald"
            title="Company Researcher"
            description="Culture, recent news, tech stack, and interview insights from web research"
          />
          <FeatureCard
            icon={<Mic className="w-6 h-6" />}
            color="amber"
            title="Interview Coach"
            description="10 likely questions with STAR-format answers crafted from your experience"
          />
        </div>
      </section>

      {/* How it works */}
      <section className="bg-gray-50 border-y">
        <div className="max-w-5xl mx-auto px-4 py-16">
          <h2 className="text-2xl md:text-3xl font-bold text-center mb-12">
            How It Works
          </h2>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <StepCard
              step={1}
              icon={<Upload className="w-6 h-6" />}
              title="Upload Your CV"
              description="Upload your CV once (PDF, DOCX, or TXT). Our AI extracts and indexes your experience, skills, and achievements."
            />
            <StepCard
              step={2}
              icon={<MessageSquare className="w-6 h-6" />}
              title="Paste a Job Description"
              description="Drop any job posting into the chat. Our agents detect it automatically and start working."
            />
            <StepCard
              step={3}
              icon={<Sparkles className="w-6 h-6" />}
              title="Get Everything Tailored"
              description="In 1-2 minutes, receive a complete application package: resume, cover letter, research, and interview prep."
            />
          </div>
        </div>
      </section>

      {/* Trust / Benefits */}
      <section className="max-w-5xl mx-auto px-4 py-16">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div className="flex items-start gap-3 p-5 rounded-xl bg-blue-50 border border-blue-100">
            <Shield className="w-6 h-6 text-blue-600 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-semibold mb-1">Your Data, Isolated</h3>
              <p className="text-sm text-gray-600">Each user gets their own Pinecone namespace. Your data is never mixed with others.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 p-5 rounded-xl bg-violet-50 border border-violet-100">
            <Zap className="w-6 h-6 text-violet-600 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-semibold mb-1">Never Fabricates</h3>
              <p className="text-sm text-gray-600">Agents only use YOUR real experience. Nothing is invented or hallucinated.</p>
            </div>
          </div>
          <div className="flex items-start gap-3 p-5 rounded-xl bg-emerald-50 border border-emerald-100">
            <Users className="w-6 h-6 text-emerald-600 flex-shrink-0 mt-0.5" />
            <div>
              <h3 className="font-semibold mb-1">Built by AI Agents</h3>
              <p className="text-sm text-gray-600">CrewAI-powered agents collaborate like a team of career coaches working just for you.</p>
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="gradient-bg text-white">
        <div className="max-w-3xl mx-auto px-4 py-16 text-center">
          <Bot className="w-12 h-12 mx-auto mb-4 opacity-80" />
          <h2 className="text-2xl md:text-3xl font-bold mb-4">
            Ready to land your next role?
          </h2>
          <p className="text-lg opacity-90 mb-8">
            Create your account, upload your CV, and let the AI agents do the heavy lifting.
          </p>
          <Link
            to="/register"
            className="inline-flex items-center gap-2 bg-white text-blue-700 px-8 py-3.5 rounded-xl text-lg font-semibold hover:bg-blue-50 transition"
          >
            Start Now — It's Free
            <ArrowRight className="w-5 h-5" />
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-gray-900 text-gray-400 text-sm text-center py-6">
        <p>ResumeCrew — Powered by CrewAI, Groq & Local Embeddings</p>
      </footer>
    </div>
  );
}

function FeatureCard({ icon, color, title, description }: {
  icon: React.ReactNode;
  color: string;
  title: string;
  description: string;
}) {
  const colorMap: Record<string, string> = {
    blue: "bg-blue-100 text-blue-600",
    violet: "bg-violet-100 text-violet-600",
    emerald: "bg-emerald-100 text-emerald-600",
    amber: "bg-amber-100 text-amber-600",
  };

  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border hover:shadow-md hover:border-blue-200 transition group">
      <div className={`w-12 h-12 rounded-xl flex items-center justify-center mb-4 ${colorMap[color] || colorMap.blue}`}>
        {icon}
      </div>
      <h3 className="font-semibold text-lg mb-2 group-hover:text-blue-600 transition">{title}</h3>
      <p className="text-gray-500 text-sm leading-relaxed">{description}</p>
    </div>
  );
}

function StepCard({ step, icon, title, description }: {
  step: number;
  icon: React.ReactNode;
  title: string;
  description: string;
}) {
  return (
    <div className="text-center">
      <div className="relative inline-flex items-center justify-center w-16 h-16 bg-blue-600 text-white rounded-2xl mb-4 shadow-lg shadow-blue-600/20">
        {icon}
        <span className="absolute -top-2 -right-2 w-6 h-6 bg-violet-500 text-white rounded-full text-xs font-bold flex items-center justify-center">
          {step}
        </span>
      </div>
      <h3 className="font-semibold text-lg mb-2">{title}</h3>
      <p className="text-gray-500 text-sm leading-relaxed">{description}</p>
    </div>
  );
}
